
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 23
 flow 3 DADOS RECEBIDOS: OK=23BYTES
 flow 3 ENVIOU DADOS23BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 112
 flow 3 DADOS RECEBIDOS: OK=112BYTES
 flow 3 ENVIOU DADOS112BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 112
 flow 3 DADOS RECEBIDOS: OK=112BYTES
 flow 3 ENVIOU DADOS112BYTES
 RUN geraBusnum
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 112
 flow 3 DADOS RECEBIDOS: OK=112BYTES
 flow 3 ENVIOU DADOS112BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 106
 flow 3 DADOS RECEBIDOS: OK=106BYTES
 flow 3 ENVIOU DADOS106BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 106
 flow 3 DADOS RECEBIDOS: OK=106BYTES
 flow 3 ENVIOU DADOS106BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 106
 flow 3 DADOS RECEBIDOS: OK=106BYTES
 flow 3 ENVIOU DADOS106BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 106
 flow 3 DADOS RECEBIDOS: OK=106BYTES
 flow 3 ENVIOU DADOS106BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 106
 flow 3 DADOS RECEBIDOS: OK=106BYTES
 flow 3 ENVIOU DADOS106BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 106
 flow 3 DADOS RECEBIDOS: OK=106BYTES
 flow 3 ENVIOU DADOS106BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 106
 flow 3 DADOS RECEBIDOS: OK=106BYTES
 flow 3 ENVIOU DADOS106BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 107
 flow 3 DADOS RECEBIDOS: OK=107BYTES
 flow 3 ENVIOU DADOS107BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 107
 flow 3 DADOS RECEBIDOS: OK=107BYTES
 flow 3 ENVIOU DADOS107BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 107
 flow 3 DADOS RECEBIDOS: OK=107BYTES
 flow 3 ENVIOU DADOS107BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 107
 flow 3 DADOS RECEBIDOS: OK=107BYTES
 flow 3 ENVIOU DADOS107BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 107
 flow 3 DADOS RECEBIDOS: OK=107BYTES
 flow 3 ENVIOU DADOS107BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 107
 flow 3 DADOS RECEBIDOS: OK=107BYTES
 flow 3 ENVIOU DADOS107BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN criaPlacod
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 179
 flow 3 DADOS RECEBIDOS: OK=179BYTES
 flow 3 ENVIOU DADOS179BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 179
 flow 3 DADOS RECEBIDOS: OK=179BYTES
 flow 3 ENVIOU DADOS179BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 112
 flow 3 DADOS RECEBIDOS: OK=112BYTES
 flow 3 ENVIOU DADOS112BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1215
 flow 3 DADOS RECEBIDOS: OK=1215BYTES
 flow 3 ENVIOU DADOS1215BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 109
 flow 3 DADOS RECEBIDOS: OK=109BYTES
 flow 3 ENVIOU DADOS109BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 1251
 flow 3 DADOS RECEBIDOS: OK=1251BYTES
 flow 3 ENVIOU DADOS1251BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 695
 flow 3 DADOS RECEBIDOS: OK=695BYTES
 flow 3 ENVIOU DADOS695BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 565
 flow 3 DADOS RECEBIDOS: OK=565BYTES
 flow 3 ENVIOU DADOS565BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 565
 flow 3 DADOS RECEBIDOS: OK=565BYTES
 flow 3 ENVIOU DADOS565BYTES
 RUN geraPlacod
 RETORNANDO TAMANHO JSON SAIDA = 108
 flow 3 DADOS RECEBIDOS: OK=108BYTES
 flow 3 ENVIOU DADOS108BYTES
 RUN buscaTime
 RETORNANDO TAMANHO JSON SAIDA = 79
 flow 3 DADOS RECEBIDOS: OK=79BYTES
 flow 3 ENVIOU DADOS79BYTES
 RUN geraBusnum
 RETORNANDO TAMANHO JSON SAIDA = 565
 flow 3 DADOS RECEBIDOS: OK=565BYTES
 flow 3 ENVIOU DADOS565BYTES
 RUN buscacomportamento
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4130
 flow 3 DADOS RECEBIDOS: OK=4130BYTES
 flow 3 ENVIOU DADOS4130BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4130
 flow 3 DADOS RECEBIDOS: OK=4130BYTES
 flow 3 ENVIOU DADOS4130BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 91
 flow 3 DADOS RECEBIDOS: OK=91BYTES
 flow 3 ENVIOU DADOS91BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4091
 flow 3 DADOS RECEBIDOS: OK=4091BYTES
 flow 3 ENVIOU DADOS4091BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4089
 flow 3 DADOS RECEBIDOS: OK=4089BYTES
 flow 3 ENVIOU DADOS4089BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4089
 flow 3 DADOS RECEBIDOS: OK=4089BYTES
 flow 3 ENVIOU DADOS4089BYTES
 RUN buscaComportamento
 RETORNANDO TAMANHO JSON SAIDA = 4089
 flow 3 DADOS RECEBIDOS: OK=4089BYTES
 flow 3 ENVIOU DADOS4089BYTES